### ISSUE TITLE
Do you have record audio example ?

### ISSUE THREAD

**Issue by iamblue** [whyengineer/esp32_snow#1]
As title. 
Thank you ~

**Comment by hzhsohn** [comment]
look this, u can try the code---------------------------------------------------------

    hal_i2c_init(0,19,18);
    hal_i2s_init(0,44100,16,2);
    WM8978_Init();
    WM8978_ADDA_Cfg(1,1); 
    WM8978_Input_Cfg(1,0,0);     
    WM8978_Output_Cfg(1,0); 
    WM8978_MIC_Gain(25);
    WM8978_AUX_Gain(0);
    WM8978_LINEIN_Gain(0);
    WM8978_SPKvol_Set(40);
    WM8978_HPvol_Set(50,50);

	short *output=(short *)malloc(1200*4);
	int output_size=1200*4*2;
	int rvlen=0;
	while(1){
           rvlen=i2s_read_bytes( I2S_NUM_0 ,(char*)output , output_size , portMAX_DELAY );
	  printf("record rvlen=%d\n",rvlen);
        }

**Comment by iamblue** [comment]
@hzhsohn  Thankyou~~
