### ISSUE TITLE
3d_show not working

### ISSUE THREAD

**Issue by allenck** [whyengineer/esp32_snow#3]
I am attempting to get the 3d_show example to work. 
however, when I attempt to connect on port 9998, the connection is reset. I see that there is a file
"3d_show.html" in the project that contains the html and javascript that presumably should be sent by the server but I cannot find any references in the code where this file is accessed. Is there something missing here?

**Comment by allenck** [comment]
The problem is becoming clearer. I was mistaken when I thought that there should be a way for the example to serve the '3d_show.html' file. All you have to do is to load it in your browser. Doing that, I was faced with a '_reference error: webSocket not defined_'. I corrected this by adding a script to load requirejs.

`<script src="https://requirejs.org/docs/release/2.3.6/r.js"></script>`
and
`const webSocket = require('ws');`

 Now,  the websocket handshake logic works and webSocket gets created and I can begin to debug why the MPU9250 logic I  added is not yet working. My changes to the project, so far,  can be reviewed at: [here](https://github.com/allenck)

**Comment by allenck** [comment]
The MPU9250 logic is working but it's not getting to the browser. problem seems to be these errors:
`Error: Mismatched anonymous define() module: function(l){function oa(){}function C(a,b){this.x=a||0;this.y=b||0}function ea(a,b,c,d,e,f,g,h,k,m){Object.defineProperty(this,"id",{value:Oe++});this.uuid=Q.generateUUID();this.name="";this.image=void 0!==a?a:ea.DEFAULT_IMAGE;this.mipmaps=[];this.mapping=void 0!==b?b:ea.DEFAULT_MAPPING;this.wrapS=void 0!==c?c:1001;this.wrapT=
void 0!==d?d:1001;this.magFilter=void 0!==e?e:1006;this.minFilter=void 0!==f?f:1008;this.anisotropy=void 0!==k?k:1;this.format=void 0!==g?g:1023;this.type=void 0!==h?h:1009;this.offset=new C(0,0);this.repeat=new C(1,1);this.generateMipmaps=!0;this.premultiplyAlpha=!1;this.flipY=!0;this.unpackAlignment=4;this.encoding=void 0!==m?m:3E3;this.version=0;this.onUpdate=null}function ga(a,b,c,d){this.x=a||0;this.y=b||0;this.z=c||0;this.w=void 0!==d?d:1}function Db(a,b,c){this.uuid=Q.generateUUID();this.width=
a;this.height=b;this.scissor=new ga(0,0,a,b);this.scissorTest=!1;this.viewport=new ga(0,0,a,b);c=c||{};void 0===c.minFi… r.js:417:17
    makeError https://requirejs.org/docs/release/2.3.6/r.js:417
    intakeDefines https://requirejs.org/docs/release/2.3.6/r.js:1503
    localRequire https://requirejs.org/docs/release/2.3.6/r.js:1695
    requirejs https://requirejs.org/docs/release/2.3.6/r.js:2046
    <anonymous> file:///home/allen/Downloads/esp32_snow/example/3d_show/3d_show.html:22

ReferenceError: THREE is not defined[Learn More] 3d_show.html:82:5

`

**Comment by whyengineer** [comment]
Hi，allenck. first of all. you must put these html file into sd card, the simple webserver lode file from SD card and use chunked way to send data to broswer. my test environment is Chorme. websocket and three.js is necessary.

**Comment by allenck** [comment]
That worked. I had not considered that option because it is a lot of 
trouble to make changes to the html because of the problem of updating 
the sd card.
